const os  = require("os")

console.log(os.type())
console.log(os.arch())
console.log(os.uptime()/60/60)
console.log(os.totalmem()/1024/1024/1024)
console.log(os.freemem()/1024**3)
console.log(os.networkInterfaces())
console.log(os.homedir())
console.log(os.userInfo())
console.log(os.constants)
